name: Build and deploy application
on:
  push:
    branches: 
      - main
jobs:
  build-deploy-nostin:
  if: github.repository == 'Nostin/diser'
  runs-on: ubuntu-latest
  environment: production
  env:
    IMAGE_TAG: australia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soil/hub:latest
  steps:
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: australia-southeast2-docker.pkg.dev 
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build and push image to GAR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_TAG }}
      - name: Deploy cloud run service
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: spectra-hub
          image: ${{ env.IMAGE_TAG }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: australia-southeast1
